package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames="code"))
public class Department implements java.io.Serializable
{
	private Integer id;
	private String code;
	private String name;
	private int level;
	private String fatherCode;
	public Department()
	{}
	public Department(String code,String name,int level)
	{
		this.code=code;
		this.name=name;
		this.level=level;
	}
	public Department(String code,String name,int level,String fatherCode)
	{
		this.code=code;
		this.name=name;
		this.level=level;
		this.fatherCode=fatherCode;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="code",unique=true,nullable=false,length=20)
	public String getCode()
	{
		return this.code;
	}
	public void setCode(String code)
	{
		this.code=code;
	}
	@Column(name="name",nullable=false,length=50)
	public String getName()
	{
		return this.name;
	}
	public void setName(String name)
	{
		this.name=name;
	}
	@Column(name="level",nullable=false)
	public int getLevel()
	{
		return this.level;
	}
	public void setLevel(int level)
	{
		this.level=level;
	}
	@Column(name="father_code",length=20)
	public String getFatherCode()
	{
		return this.fatherCode;
	}
	public void setFatherCode(String fatherCode)
	{
		this.fatherCode=fatherCode;
	}
}
