package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DepartmentRoleUser generated by hbm2java
 */
@Entity
@Table(name="department_role_user",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames={"department_code", "role_code", "user_code"}))
public class DepartmentRoleUser implements java.io.Serializable
{
	private Integer id;
	private String userCode;
	private String roleCode;
	private String departmentCode;
	private char valid;
	public DepartmentRoleUser()
	{}
	public DepartmentRoleUser(String userCode,String roleCode,String departmentCode,char valid)
	{
		this.userCode=userCode;
		this.roleCode=roleCode;
		this.departmentCode=departmentCode;
		this.valid=valid;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="user_code",nullable=false,length=20)
	public String getUserCode()
	{
		return this.userCode;
	}
	public void setUserCode(String userCode)
	{
		this.userCode=userCode;
	}
	@Column(name="role_code",nullable=false,length=20)
	public String getRoleCode()
	{
		return this.roleCode;
	}
	public void setRoleCode(String roleCode)
	{
		this.roleCode=roleCode;
	}
	@Column(name="department_code",nullable=false,length=20)
	public String getDepartmentCode()
	{
		return this.departmentCode;
	}
	public void setDepartmentCode(String departmentCode)
	{
		this.departmentCode=departmentCode;
	}
	@Column(name="valid",nullable=false,length=1)
	public char getValid()
	{
		return this.valid;
	}
	public void setValid(char valid)
	{
		this.valid=valid;
	}
}
