package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames="code"))
public class Role implements java.io.Serializable
{
	private Integer id;
	private String code;
	private String name;
	public Role()
	{}
	public Role(String code,String name)
	{
		this.code=code;
		this.name=name;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="code",unique=true,nullable=false,length=20)
	public String getCode()
	{
		return this.code;
	}
	public void setCode(String code)
	{
		this.code=code;
	}
	@Column(name="name",nullable=false,length=50)
	public String getName()
	{
		return this.name;
	}
	public void setName(String name)
	{
		this.name=name;
	}
}
