package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames="code"))
public class User implements java.io.Serializable
{
	private Integer id;
	private String code;
	private String name;
	private String email;
	private String phone;
	private char gender;
	public User()
	{}
	public User(String code,String name,String email,String phone,char gender)
	{
		this.code=code;
		this.name=name;
		this.email=email;
		this.phone=phone;
		this.gender=gender;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="code",unique=true,nullable=false,length=20)
	public String getCode()
	{
		return this.code;
	}
	public void setCode(String code)
	{
		this.code=code;
	}
	@Column(name="name",nullable=false,length=20)
	public String getName()
	{
		return this.name;
	}
	public void setName(String name)
	{
		this.name=name;
	}
	@Column(name="email",nullable=false,length=60)
	public String getEmail()
	{
		return this.email;
	}
	public void setEmail(String email)
	{
		this.email=email;
	}
	@Column(name="phone",nullable=false,length=11)
	public String getPhone()
	{
		return this.phone;
	}
	public void setPhone(String phone)
	{
		this.phone=phone;
	}
	@Column(name="gender",nullable=false,length=1)
	public char getGender()
	{
		return this.gender;
	}
	public void setGender(char gender)
	{
		this.gender=gender;
	}
}
