package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WebPathPrivilege generated by hbm2java
 */
@Entity
@Table(name="web_path_privilege",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames={"department_code", "role_code", "user_code", "web_path_id"}))
public class WebPathPrivilege implements java.io.Serializable
{
	private Integer id;
	private String departmentCode;
	private String roleCode;
	private String userCode;
	private int webPathId;
	private char accessible;
	public WebPathPrivilege()
	{}
	public WebPathPrivilege(int webPathId,char accessible)
	{
		this.webPathId=webPathId;
		this.accessible=accessible;
	}
	public WebPathPrivilege(String departmentCode,String roleCode,String userCode,int webPathId,char accessible)
	{
		this.departmentCode=departmentCode;
		this.roleCode=roleCode;
		this.userCode=userCode;
		this.webPathId=webPathId;
		this.accessible=accessible;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="department_code",length=20)
	public String getDepartmentCode()
	{
		return this.departmentCode;
	}
	public void setDepartmentCode(String departmentCode)
	{
		this.departmentCode=departmentCode;
	}
	@Column(name="role_code",length=20)
	public String getRoleCode()
	{
		return this.roleCode;
	}
	public void setRoleCode(String roleCode)
	{
		this.roleCode=roleCode;
	}
	@Column(name="user_code",length=20)
	public String getUserCode()
	{
		return this.userCode;
	}
	public void setUserCode(String userCode)
	{
		this.userCode=userCode;
	}
	@Column(name="web_path_id",nullable=false)
	public int getWebPathId()
	{
		return this.webPathId;
	}
	public void setWebPathId(int webPathId)
	{
		this.webPathId=webPathId;
	}
	@Column(name="accessible",nullable=false,length=1)
	public char getAccessible()
	{
		return this.accessible;
	}
	public void setAccessible(char accessible)
	{
		this.accessible=accessible;
	}
}
