package com.hibernate.entity;
// Generated 2017-2-13 22:14:29 by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WebPath generated by hbm2java
 */
@Entity
@Table(name="web_path",catalog="orange",uniqueConstraints=@UniqueConstraint(columnNames="path"))
public class WebPath implements java.io.Serializable
{
	private Integer id;
	private String path;
	private String description;
	public WebPath()
	{}
	public WebPath(String path)
	{
		this.path=path;
	}
	public WebPath(String path,String description)
	{
		this.path=path;
		this.description=description;
	}
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(name="id",unique=true,nullable=false)
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id=id;
	}
	@Column(name="path",unique=true,nullable=false,length=100)
	public String getPath()
	{
		return this.path;
	}
	public void setPath(String path)
	{
		this.path=path;
	}
	@Column(name="description",length=100)
	public String getDescription()
	{
		return this.description;
	}
	public void setDescription(String description)
	{
		this.description=description;
	}
}
